### ISSUE TITLE
Kompose username/password?

### ISSUE THREAD

**Issue by bkcummins** [kubernetes-sigs/aws-iam-authenticator#137]
I'm working through our first Kubernetes deployment from a MacOS terminal into worker nodes managed by AWS EKS.  

Everything in the AWS EKS documentation is working as explained; however, I was trying to deploy a docker-compose.yml using `Kompose up` and am asked for a Username and Password.  

Any idea what I would use to create a Username and Password?  Is this referring to a Kubernetes service account or would it be mapped to an IAM user account? 

I tried to mapUsers to a IAM userarn, but I don't see what password would be used.
https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html

`kubectl edit -n kube-system configmap/aws-auth`

I was unable to satisfy it with an IAM user and console password.

Any help clarifying would get great appreciated. 

Thx in advance!

**Comment by mumoshu** [comment]
@bkcummins Hey! Would you mind sharing us full log messages until you were asked for username and password?

I was wondering if `kompose up` would automatically build a docker image, and before deploying to to K8S, try to push it to your a docker registry? In case your registry requires authentication, you would have been asked for username and password for the docker registry.

**Comment by bkcummins** [comment]
@mumoshu Also, in this instance the images for these services are already built and published to a DTR.  They're not spec'd to `build` in docker-compose.yml.

**Comment by mattlandis** [comment]
I haven't used kompose myself, but I took a look at the source and it looks like they are using an old version of [client-go](https://github.com/kubernetes/kompose/tree/master/vendor/k8s.io/client-go/1.4).  Since it doesn't have the new exec based auth provider that may be causing the issue.

I pulled down a copy of kubectl v1.4.1 and used it to try and get pods against a eks cluster.  It prompts for username and password too.

They have an [open issue](https://github.com/kubernetes/kompose/issues/175) to move to client-go for interactions.  I've added a comment on that issue to also upgrade the version of client-go being used.

**Comment by bkcummins** [comment]
@mattlandis thx so much for the explanation! we just moved on w/o kompose.

**Comment by RichardBronosky** [comment]
I had this issue too even though my `kubectl` calls were fine. Turns out that the root user did not have the access needed. so I copied the ~/.kube/config file to the root user's home.

```
sudo mkdir -p /root/.kube; sudo cp ~/.kube/config /root/.kube/
ip="$(ip route get 1 | awk 'NR==1{print $7}')"
sudo -H kompose up --server https://$ip:6443
```
And I am using `sudo` because my user can't access `/var/run/docker.sock`
