### ISSUE TITLE
Relationship between artifacts in `amazon-eks.s3-us-west-2.amazonaws.com` and here

### ISSUE THREAD

**Issue by chenrui333** [kubernetes-sigs/aws-iam-authenticator#199]
I found there are multiple versions of artifacts (`aws-iam-authenticator`) are hosted in https://amazon-eks.s3-us-west-2.amazonaws.com, but the version seems pretty different from the ones in this repo. 

So my question is what is the artifact publishing process for the AWS one, and the relationship to this repo.

Also, I wonder if I can have a good strategy to get notified to keep my `aws-iam-authenticator` always up to date.

Thanks!

**Comment by derwasp** [comment]
👍 on this. I thought on [creating a chocolatey package](https://github.com/kubernetes-sigs/aws-iam-authenticator/issues/194) for `aws-iam-authenticator` and I don't even know which version to take now.

Also interesting is the following:

A binary taken from [the AWS' documentation](https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html )`aws-iam-authenticator version` gives `{}` as a response, while a version downloaded from github returns a corresponding version.

![image](https://user-images.githubusercontent.com/10754345/54131762-4be6e000-4413-11e9-8acc-2fd83cf09408.png)

Why is this? Does it mean there will be no version for the binary that is distributed by AWS?

@nckturner maybe you can help us here? I saw your [PR](https://github.com/kubernetes-sigs/aws-iam-authenticator/pull/187) where you are returning `unversioned` instead of the empty version.

**Comment by nckturner** [comment]
Thanks for pointing this out.  The eks build process has been fixed, and binaries we publish will start showing a version (and we'll republish the most recent).
