### ISSUE TITLE
Always getting error: You must be logged in to the server (Unauthorized)

### ISSUE THREAD

**Issue by beetlikeyg083** [kubernetes-sigs/aws-iam-authenticator#275]
I am currently playing around with AWS EKS
But I always get `error: You must be logged in to the server (Unauthorized)` when trying to run `kubectl cluster-info` command.

I have read a lot of AWS documentation and look at lots of similar issues who face the same problem. Unfortunately, none of them resolves my problem. 

So, this is what I did
1. create a user to access _aws-cli_ name `crop-portal`
2. create a role for EKS name `crop-cluster`
3. create EKS cluster via AWS console with the role `crop-cluster` name` crop-cluster`(cluster and role have the same name)
4. run AWS configure for user `crop-portal`
5. run `aws eks update-kubeconfig --name crop-cluster` to update the kube config
6. run `aws sts assume-role --role-arn crop-cluster-arn --role-session-name eks-access`
7. copy _accessKey_, _secreyKey_ and _sessionToken_ into env variables _AWS_ACCESS_KEY_ID_, _AWS_SECRET_ACCESS_KEY_ and _AWS_SESSION_TOKEN_ accordingly
8. run `aws sts get-caller-indentity` and now the result says it used assume role already
```
{
    "UserId": "AROAXWZGX5HOBZPVGAUKC:botocore-session-1572604810",
    "Account": "529972849116",
    "Arn": "arn:aws:sts::529972849116:assumed-role/crop-cluster/botocore-session-1572604810"
}
```
6. run `kubectl cluster` and always `get error: You must be logged in to the server (Unauthorized)`

when I run `aws-iam-authenticator token -i crop-cluster`, it gave me the token and
when I run `aws-iam-authenticator verify -t token -i crop-portal`, it also passed

`&{ARN:arn:aws:sts::529972849116:assumed-role/crop-cluster/1572605554603576170 CanonicalARN:arn:aws:iam::529972849116:role/crop-cluster AccountID:529972849116 UserID:AROAXWZGX5HOBZPVGAUKC SessionName:1572605554603576170}`

I don't know what is wrong or what I miss. I try so hard to get it works but I really don't know what to do after this.
Some people suggest creating a cluster with awscli instead of GUI. I tried both methods and none of them work. Either creating with awscli or GUI is the same for me.

Please someone helps :(

**Comment by swoldemi** [comment]
Have you tried, before doing `run kubectl cluster and always get error: You must be logged in to the server (Unauthorized)`, running `aws eks update-kubeconfig -name crop-cluster`?

**Comment by beetlikeyg083** [comment]
@swoldemi I did. `aws eks update-kubeconfig -name crop-cluster` is in my step number 5.

**Comment by swoldemi** [comment]
> @swoldemi I did. `aws eks update-kubeconfig -name crop-cluster` is in my step number 5.

I guess I mean't updating your kubeconfig after you assume the role?

**Comment by yunghoy** [comment]
I've tried to solve this case, used root ARN and custom ARN, adding user into role, creating cluster with root, creating cluster with custom id, creating cluster in console with both id, using aws, using aws-iam-authenticator, using custom profile in .aws/config, changing token in .kube/config to real token, etc., etc., etc.

aws sts get-caller-identity worked.
aws eks --region us-west-2 describe-cluster --name eks --query cluster worked.
aws eks --region us-west-2 update-kubeconfig --name eks --role-arn arn:aws:iam::*************:role/eksrole worked.

All information seems correct but I was not able to achieve to access kubernetes console.
Thus, I will make this issue is opened.

**Comment by yunghoy** [comment]
If here is an AWS developers who are in EKS, please prepare your new linux machine and get kubectl, aws and aws-iam-authenticator, and make a new AWS account and try to create a new EKS cluster. And can you update EKS document on AWS website?
Thanks.

**Comment by eddiezane** [comment]
Might not be the same cause but I just ran into this and in my case I created my cluster on a different computer as a different IAM user than the computer/user I was trying to access the cluster with.

The instructions from [here](https://aws.amazon.com/premiumsupport/knowledge-center/eks-api-server-unauthorized-error/) helped me figure out that I needed to add the user that didn't create the cluster to the configmap.

From 2nd computer:
```
aws sts get-caller-identity

{
    "UserId": "foo",
    "Account": "bar",
    "Arn": "arn:aws:iam::bar:user/SECOND"
}

// Grab ARN
```

From computer/user that created cluster:
```
kubectl -n kube-system edit configmap aws-auth

// Set mapUsers to
mapUsers: |
  - userarn: arn:aws:iam::bar:user/SECOND
    username: testuser
    groups:
      - system:masters
```

If you're hitting this my suspicion would be that you created the cluster as a different user/role than you are trying to access with. Maybe instead of using the web console try creating with aws-cli or eksctl.

Hope this helps someone.

**Comment by s1dequest** [comment]
Had a similar issue recently. It ended up being something simple that I may not have noticed for a while had there not been another engineer on the team who had run into it before.

The rolearn I had added was a copy & paste of the ARN shown in the console. So it looked something like this:
```apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  
  mapRoles: |
  # ...
  - rolearn: arn:aws:iam::${number}:role/${path}/${role_name}
  # ...
```
Turns out you are not supposed to add the ARN path here (not sure why). Removing it, so now we had `- rolearn ... :role/${role_name}`, fixed the issue for me.

**Comment by yacinelazaar** [comment]
![image](https://user-images.githubusercontent.com/1111396/100791793-00137000-341a-11eb-90a6-b91df91b9b8a.png)
@s1dequest Yeah the path for my roles is already empty and the issue still persists.

**Comment by francotel** [comment]
I have the same problem with the assumed role? I tried ti add the role arn but not the assume role beacuse dont let me something like that:
`eksctl create iamidentitymapping \
  --cluster eks-cluster-tupana-dev \
  --arn "arn:aws:iam::176907347234:role/service-role/codebuild-images-profile-tupana-dev" \
  --username admin \
  --group system:masters \
  --profile tupana-dev --region us-east-1`

**Comment by sarathm54** [comment]
I got the same error and resolved.
i created eks cluster from aws console, and configured aws cli in my laptop with deferent iam user, this caused me the same error. to resolve this i created cli access security credentials for the same user which i created the eks cluster, when i use this credentials to clonfigure my aws cli everything fine. now its working perfectly.

thanks

![image](https://user-images.githubusercontent.com/37060759/116005721-e3284500-a625-11eb-91df-cbf6f646220d.png)

**Comment by aditj95** [comment]
Using the assumed-role didn't work for me. Had to use the actual "role" (from IAM click on the role and get the arn). Remove the path between role/<path>/<ROLE_NAME>

I.e.

`    groups: "system:masters"
    rolearn: "arn:aws:iam::<account>:role/<ROLE_NAME>"
    username: "<ROLE_NAME>"`

**Comment by chitikenasatish** [comment]
just run the below command with proper region and cluster name . it worked. 
aws eks update-kubeconfig --region _us-west-2_ --name _my-cluster_
